name: Test Terraform Deploy Success
on:
  workflow_dispatch: 
  push:
    branches:
      - main
env:
  EXTERNAL_PORT: ${{ secrets.EXTERNAL_PORT }}
  EXTERNAL_PORT_VAR: "ext_port"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format tf files
        run: terraform fmt
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Init providers
        run: terraform init
      - name: Create tfvars
        run: touch terraform.tfvars || true && echo '${{ env.EXTERNAL_PORT_VAR}} = ${{ env.EXTERNAL_PORT}}' > terraform.tfvars
      - name: Build plan file
        run: terraform plan -out=plan
      - name: Upload plan file
        uses: actions/upload-artifact@v3
        with:
          name: plan-files
          path: |
            plan
            .terraform.lock.hcl
            terraform.tfvars
            terraform.tfstate
  apply-and-test:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get build file
        uses: actions/download-artifact@v3
        with:
          name: plan-files
      - name: Apply terraform infra
        uses: PedroAlmeidacode/composite-action-apply-tf@v2.1.1
        with:
          plan-file-path: ./plan
      - name: Get link output
        id: link
        run: echo "URL=$(terraform output -raw host-testing-link)" >> $GITHUB_OUTPUT
      - name: Test container
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: ${{ steps.link.outputs.URL }}
          responseCode: '200'
          timeout: 10000
          interval: 500

